node {
    stage("Checkout") {
        checkout scm
    }
    stage("Building image") {
        dir("employee") {
            docker.build('${JOB_NAME}', '-f Dockerfile .')
        }
    }
    stage("Pushing image to ECR") {
        docker.withRegistry('', 'rachitsrivastava007') {
            docker.image('${JOB_NAME}').push('${BUILD_ID}')
        }
    }
}
