pipeline {
  environment {
    registry = "rachitsrivastava007/employee"
    registryCredential = 'rachitsrivastava007'
    dockerImage = ''
  }
  agent any
  stages {
    stage('Building image') {
      steps{
       dir("employee") {
        script {
          docker.build('rachitsrivastava007/${JOB_NAME}', '-f Dockerfile .')
        }
       }
      }
    }
    
    
    stage('Push image') {
      steps{
    /* Finally, we'll push the image with two tags:
    * First, the incremental build number from Jenkins
    * Second, the 'latest' tag. */
  script {
    docker.withRegistry('', 'rachitsrivastava007') {
    withCredentials([usernamePassword( credentialsId: 'rachitsrivastava007', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
    sh "docker login -u ${USERNAME} -p ${PASSWORD}"
    sh "echo ${USERNAME}"
    sh "echo ${PASSWORD}"
    docker.image('rachitsrivastava007/${JOB_NAME}').push('${BUILD_ID}')
    }
    }
      }
    }
    }
    
    stage('Run docker') {
      steps{
        sh "docker run -d -e CONFIG_FILE=/app/config.yaml $registry:$BUILD_NUMBER"
      }
    }
  }
}
