pipeline {
  environment {
    registry = "rachitsrivastava007/employee"
    registryCredential = 'rachitsrivastava007'
    dockerImage = ''
  }
  agent any
  stages {
    stage('Building image') {
      steps{
       dir("employee") {
        script {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
        }
       }
      }
    }
    stage('Run docker') {
      steps{
        docker.image('$registry:$BUILD_NUMBER').withRun('-e CONFIG_FILE=/app/config.yaml') {}
      }
    }

  }
}
